name: Run integration DEV

on:
  push:
  workflow_dispatch:

jobs:
  manual-integration-dev:
    uses: ./.github/workflows/call_run_integration.yaml
    with:
      environment: dev
    secrets: inherit
    